# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"/\n\x12\x43hatMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\x13\x43hatMessageResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t2R\n\x0b\x43hatService\x12\x43\n\x08\x42idiChat\x12\x18.chat.ChatMessageRequest\x1a\x19.chat.ChatMessageResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGEREQUEST']._serialized_start=20
  _globals['_CHATMESSAGEREQUEST']._serialized_end=67
  _globals['_CHATMESSAGERESPONSE']._serialized_start=69
  _globals['_CHATMESSAGERESPONSE']._serialized_end=117
  _globals['_CHATSERVICE']._serialized_start=119
  _globals['_CHATSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
