# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/chat.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/chat.proto\x12\x04\x63hat\"(\n\x0b\x43hatMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2e\n\x0b\x43hatService\x12,\n\x08Receiver\x12\x0b.chat.Empty\x1a\x11.chat.ChatMessage0\x01\x12(\n\x06Sender\x12\x11.chat.ChatMessage\x1a\x0b.chat.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=27
  _globals['_CHATMESSAGE']._serialized_end=67
  _globals['_EMPTY']._serialized_start=69
  _globals['_EMPTY']._serialized_end=76
  _globals['_CHATSERVICE']._serialized_start=78
  _globals['_CHATSERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
